// define types
export const UPDATE_EMAIL = 'UPDATE_EMAIL'
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const LOGIN = 'LOGIN'
export const SIGNUP = 'SIGNUP'
export const SUBMITDATA = 'SUBMITDATA'
export const ERROR = 'ERROR'
export const REFRESH = 'REFRESH'
export const FETCH_ORDER_DATA = 'FETCH_ORDER_DATA'
export const GET_CURRENT_USER = 'GET_CURRENT_USER'
